// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fixtures.Azure.AcceptanceTestsAzureParameterGrouping.Models
{
    using System;

    /// <summary>
    /// Additional parameters for the postMultipleParameterGroups operation.
    /// </summary>
    public partial class FirstParameterGroup
    {
        /// <summary>
        /// Initializes a new instance of the FirstParameterGroup class.
        /// </summary>
        /// <param name='headerOne'>
        /// </param>
        /// <param name='queryOne'>
        /// Query parameter with default
        /// </param>
        public FirstParameterGroup(string headerOne = default(string), int? queryOne = default(int?))
        {
            HeaderOne = headerOne;
            QueryOne = queryOne;
        }

        /// <summary>
        /// </summary>
        public string HeaderOne {get;set;}

        /// <summary>
        /// Query parameter with default
        /// </summary>
        public int? QueryOne {get;set;}

    }
}
