// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fixtures.Azure.AcceptanceTestsAzureParameterGrouping.Models
{
    using System;

    /// <summary>
    /// Additional parameters for the postRequired operation.
    /// </summary>
    public partial class ParameterGroupingPostRequiredParameters
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ParameterGroupingPostRequiredParameters class.
        /// </summary>
        /// <param name='body'>
        /// </param>
        /// <param name='header'>
        /// </param>
        /// <param name='query'>
        /// Query parameter with default
        /// </param>
        /// <param name='path'>
        /// Path parameter
        /// </param>
        public ParameterGroupingPostRequiredParameters(int? body, string path, string header = default(string), int? query = default(int?))
        {
            Body = body;
            Header = header;
            Query = query;
            Path = path;
        }

        /// <summary>
        /// </summary>
        public int? Body {get;set;}

        /// <summary>
        /// </summary>
        public string Header {get;set;}

        /// <summary>
        /// Query parameter with default
        /// </summary>
        public int? Query {get;set;}

        /// <summary>
        /// Path parameter
        /// </summary>
        public string Path {get;set;}

    }
}
