// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fixtures.Azure.AcceptanceTestsAzureParameterGrouping.Models
{
    using System;

    /// <summary>
    /// Additional parameters for the postOptional operation.
    /// </summary>
    public partial class ParameterGroupingPostOptionalParameters
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ParameterGroupingPostOptionalParameters class.
        /// </summary>
        /// <param name='header'>
        /// </param>
        /// <param name='query'>
        /// Query parameter with default
        /// </param>
        public ParameterGroupingPostOptionalParameters(string header = default(string), int? query = default(int?))
        {
            Header = header;
            Query = query;
        }

        /// <summary>
        /// </summary>
        public string Header {get;set;}

        /// <summary>
        /// Query parameter with default
        /// </summary>
        public int? Query {get;set;}

    }
}
