// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fixtures.Azure.AcceptanceTestsAzureParameterGrouping.Models
{
    using System;

    /// <summary>
    /// Additional parameters for the postMultipleParameterGroups operation.
    /// </summary>
    public partial class SecondParameterGroup
    {
        /// <summary>
        /// Initializes a new instance of the SecondParameterGroup class.
        /// </summary>
        /// <param name='headerTwo'>
        /// </param>
        /// <param name='queryTwo'>
        /// Query parameter with default
        /// </param>
        public SecondParameterGroup(string headerTwo = default(string), int? queryTwo = default(int?))
        {
            HeaderTwo = headerTwo;
            QueryTwo = queryTwo;
        }

        /// <summary>
        /// </summary>
        public string HeaderTwo {get;set;}

        /// <summary>
        /// Query parameter with default
        /// </summary>
        public int? QueryTwo {get;set;}

    }
}
